name: Create Release

on:
  push:
    tags:
      - "[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build userscript
        run: npm run build
        env:
          VERSION: ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            dist/jma.user.js
          generate_release_notes: true
          draft: false
          prerelease: false
