name: Create Release

on:
  push:
    tags:
      - "[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build userscript
        run: npm run build
        env:
          VERSION: ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            dist/jma.user.js
          generate_release_notes: true
          draft: false
          prerelease: false
